default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: interacti_blog_development
  username: postgres
  password: fatema

test:
  <<: *default
  database: interacti_blog_test
  username: postgres
  password: fatema

production:
  <<: *default
  database: interacti_blog_production
  username: postgres
  password: fatema
