default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_blog_app_development

test:
  <<: *default
  database: your_blog_app_test

production:
  <<: *default
  database: interacti_blog_production
  username: interacti_blog
  password: <%= ENV["INTERACTI_BLOG_DATABASE_PASSWORD"] %>
