default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: interacti_blog_development
  username: postgres
  password: fatema

test:
  <<: *default
  database: interacti_blog_test

production:
  <<: *default
  database: interacti_blog_production
  username: interacti_blog
  password: <%= ENV["INTERACTI_BLOG_DATABASE_PASSWORD"] %>
